### ISSUE TITLE
Version 2.0 roadmap

### ISSUE THREAD

**Issue by mbrubeck** [reem/rust-ordered-float#69]
Breaking API changes:

- [x] Remove fallible `From` impl (#57).
- [x] Remove deprecated type aliases.

Increases minimum Rust version from 1.28:

- [x] Use `TryFrom` to replace the fallible `From` impl (#56). Requires Rust 1.34.
- [x] Add a `const fn` constructor (#67, #68). Requires Rust 1.31.
